import { Inter } from 'next/font/google'
import './globals.css'
import AppHeader from '@/components/AppHeader'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#F7F7F7] h-screen min-h-screen w-full`}>
        <div className={`w-full flex flex-col items-start h-full bg-[#F7F7F7]`}>
          <AppHeader />
          <div className='flex flex-col flex-1 w-full overflow-y-auto'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
